# Generated by Django 3.2.6 on 2021-08-12 10:08

from django.db import migrations, models
import django.db.models.deletion
import vl_core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='vl_snippet_snippet', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, help_text='Displayed only in the admin', max_length=200, verbose_name='Title')),
                ('content', models.TextField(blank=True, help_text='You can insert html, javascript code or data, if you use Template', verbose_name='Code or data')),
                ('reformed_content', models.TextField(blank=True, editable=False)),
                ('is_video', models.BooleanField(default=False, help_text='Select if you want to insert video (from youtube)', verbose_name='Is video?')),
                ('tag_id', models.CharField(blank=True, help_text='Can be useful for anchor or other tasks', max_length=100, verbose_name='ID')),
                ('tag_classes', models.CharField(blank=True, help_text='Separate with blank. It can be useful for adding style to a block if the available classes are known, or simply wrapping it in a tag with any class', max_length=200, verbose_name='Classes')),
                ('template', vl_core.fields.TemplateField(blank=True, max_length=255, verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Snippet',
                'verbose_name_plural': 'Snippets',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
